<a href="https://colab.research.google.com/github/shayari21/Udacity--Secure-AI/blob/master/Building_Private_Databases.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GENERATE PARARLLEL DATABASE

Here we remove one entry from database iteratively and create parallel databases to check the definition of differential privacy.

In [0]:
pip install syft


In [3]:
import torch

#creating Original database

num_entries=5000
db=torch.rand(num_entries)>0.5
db

tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8)

In [12]:
db[3:]

tensor([1, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8)

In [18]:
def get_parallel_db(db,remove_index):
  
  
  return torch.cat((db[0:remove_index],db[remove_index+1:]))

def get_parallel_dbs(db):
  
  parallel_dbs = list()

  for i in range(len(db)):
    pdb=get_parallel_db(db,i)
    parallel_dbs.append(pdb)
    
  return parallel_dbs

pdbs= get_parallel_dbs(db)
pdbs  

[tensor([0, 1, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0

In [0]:
def create_db_and_parallels(num_entries):
  
  db=torch.randn(num_entries) > 0.5
  pdbs=get_parallel_dbs(db)
  
  return db, pdbs


In [27]:

db , pdbs= create_db_and_parallels(20)
pdbs

[tensor([1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,